version: 2

updates:
  - package-ecosystem: npm
    directory: /
    target-branch: "dev"
    schedule:
      interval: weekly
    labels:
      - "npm"
      - "dependencies" 

  - package-ecosystem: github-actions
    directory: /
    target-branch: "dev"
    schedule:
      interval: weekly
    labels:
      - "github_actions"
      - "dependencies"   