name: Deploy to vercel (Development)

on:
  push:
    branches:
      - dev
    tags:
      - "!*"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: install dependencies
        run: npm install

      - name: deploy to Vercel
        env:
          NODE_ENV: production
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          npx vercel --token ${VERCEL_TOKEN}
