name: Verify pr build

on:
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: install dependencies
        run: npm install

      - name: lint
        run: npm run lint --if-present

      - name: build
        env:
          NODE_ENV: production
        run: npm run build
